version: "3.9"

services:
  srsenb:
    image: shubhamtatvamasi/srsran-demo
    container_name: srsenb
    networks:
      srs_net:
        ipv4_address: 172.50.50.10
    command:
      - srsenb
      - --enb.mcc=505
      - --enb.mnc=08
      - --enb.mme_addr=192.168.60.142
      - --enb.gtp_bind_addr=192.168.60.1
      - --enb.s1c_bind_addr=192.168.60.1
      - --rf.device_name=zmq
      - --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6"

  srsue:
    image: shubhamtatvamasi/srsran-demo
    container_name: srsue
    depends_on: 
      - srsenb
    networks:
      srs_net:
        ipv4_address: 172.50.50.11
    command:
      - srsue
      - --gw.netns=ue1
      - --usim.algo=milenage
      - --usim.opc=63BFA50EE6523365FF14C1F45F88737D
      - --usim.imsi=505080123456781
      - --usim.imei=353490069873311
      - --rf.device_name=zmq
      - --rf.device_args="tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6"
      # - --rf.dl_earfcn=37750

networks:
  srs_net:
    ipam:
      driver: default
      config:
        - subnet: "172.50.50.0/24"
