---
- name: Stop srsue container
  become: yes
  community.docker.docker_container:
    name: srsue
    state: absent

- name: Stop srsenb container
  become: yes
  community.docker.docker_container:
    name: srsenb
    state: absent
