- name: Stop srsRAN
  hosts: all
  become: yes
  tasks:

  - name: Stop srsue container
    community.docker.docker_container:
      name: srsue
      state: absent

  - name: Stop srsenb container
    community.docker.docker_container:
      name: srsenb
      state: absent
